services:
    api:
        build: .
        depends_on:
            - postgres
        ports:
            - 8000:8000
        volumes:
            - ./:/usr/src/app:ro
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        # env_file:
        #     - ./.env
        environment:
            - DATABASE_HOSTNAME=postgres
            - DATABASE_PORT=5432
            - DATABASE_PASSWORD=manthan03583
            - DATABASE_NAME=fastapi
            - DATABASE_USERNAME=postgres
            - SECRET_KEY=4589a929f6a348a58a28e031716ae9247a98f97e1dcf130e7f7e22ac838c2f71
            - ALGORITHM=HS256
            - ACCESS_TOKEN_EXPIRE_MINUTES=30
        entrypoint: /usr/src/app/start-dev.sh

    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=manthan03583
            - POSTGRES_DB=fastapi
        
        volumes:
            - postgres-db:/var/lib/postgresql/data
volumes:
    postgres-db: