name: Build and Deploy Code

# on: [push, pull_request]
  # push:
  #   # branches: ["main", "another branch", "feature branch"]
  #   branches:
  #     - "main"
  #     - "another branches"
  # pull_request:
  #   branches:
  #     - "test_branch"

on: [push, pull_request]

jobs:
  job1:
    env:
      DATABASE_HOSTNAME=localhost
      DATABASE_PORT=5432
      DATABASE_PASSWORD=Moharana123
      DATABASE_NAME=fastapi
      DATABASE_USERNAME=postgres
      SECRET_KEY=4589a929f6a348a58a28e031716ae9247a98f97e1dcf130e7f7e22ac838c2f71
      ALGORITHM=HS256
      ACCESS_TOKEN_EXPIRE_MINUTES=30
    runs-on: ubuntu-24.04
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      # - name: hello world!!
      #   run: echo "hello world!!"

      - name: Install python version 3.12.3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      
      - name: update pip
        run: python3 -m pip install --upgrade pip

      - name: install all dependencies
        run: pip install -r requirements.txt
      
      - name: test with pytest
        run: 
          pip install pytest
          pytest -v -s
